### ISSUE TITLE
How can I get the coupon code?

### ISSUE THREAD

**Issue by Jabberrwocky** [kfrancis/Chargify2#5]
Hi,

Until I upgraded to the latest version of Chargify2, I could use the following line of code to get the coupon code:

call["call"]["request"]["signup"]["coupon_code"]

Is it still possible to get the coupon code? I expected it to be here, but it was not:

call.request.signup.coupon_code

Thanks.

**Comment by Jabberrwocky** [comment]
I figured out how to add this feature to your project and have submitted a [pull request](https://github.com/kfrancis/Chargify2/pull/6).

**Comment by kfrancis** [comment]
Looks good! :shipit:
